# @package _global_
defaults:
  - override /datamodule: advection_diffusion_multichannel_64_64
  - override /encoder@model.encoder: permute_concat
  - override /decoder@model.decoder: channels_last
  - override /processor@model.processor: vit_large
  - _self_

experiment_name: epd_crps_ps1

datamodule:
  use_normalization: false
  batch_size: 16

logging:
  wandb:
    enabled: true

optimizer:
  learning_rate: 0.0002

model:
  train_in_latent_space: false
  n_members: 10
  encoder:
    with_constants: true
  processor:
    hidden_dim: 256
    n_noise_channels: 4096
    spatial_resolution: [64, 64]
    patch_size: 1
  loss_func:
    _target_: autocast.losses.ensemble.CRPSLoss
  train_metrics:
    crps:
      _target_: autocast.metrics.ensemble.CRPS

trainer:
  max_epochs: 25
