name: "${.optimizer}_${.learning_rate}_${.scheduler}"
optimizer: "psgd"
learning_rate: 1e-4
weight_decay: 0.0
betas: [0.9]
precondition_frequency: 64
precondition_frequency_decay: 0.999
precondition_size: 4096
preconditioner_update_probability: null
max_size_triangular: 2048
min_ndim_triangular: 2
memory_save_mode: null
momentum_into_precond_update: true
merge_dims: false
split: false
store_triu_as_line: true
foreach: true
q_dtype: "float32"
stochastic_schedule: true
storage_dtype: "float32"
precond_init_scale: 1.0
precond_lr: 0.1
scheduler: "cosine"
grad_clip: 1.0
