# @package _global_
defaults:
  - /distributed: single_gpu_slurm
  - override /datamodule: advection_diffusion
  - override /model: autoencoder_dc_large
  - override /optimizer: psgd
  - _self_

experiment_name: ae_dc_large

datamodule:
  # use_normalization: false
  # batch_size: 64
  use_normalization: true
  batch_size: 256

model:
  encoder:
    periodic: true
  decoder:
    periodic: true

logging:
  wandb:
    enabled: false

optimizer:
  learning_rate: 1e-5
  weight_decay: 0.0
  scheduler: cosine

trainer:
  gradient_clip_val: 1.0