# ~5M params
_target_: autocast.processors.SwinViTProcessor
in_channels: null
out_channels: null
spatial_resolution: auto
hidden_dim: 18
encoder_depths: [2, 2, 6, 2]
encoder_num_heads: [3, 6, 12, 24]
decoder_depths: [2, 6, 2, 2]
decoder_num_heads: [24, 12, 6, 3]
patch_size: 4
window_size: [7, 7]
n_noise_channels: 256
drop_path: 0.1
groups: 12
use_ada_ln: true
zero_init: true
