# ~80M params
_target_: autocast.processors.AzulaViTProcessor
in_channels: auto
out_channels: auto
spatial_resolution: auto
hidden_dim: 768
num_heads: 4
n_layers: 10
patch_size: 4
temporal_method: none
n_noise_channels: 256
include_global_cond: false
