_target_: autocast.data.datamodule.SpatioTemporalDataModule
data_path: "${oc.env:AUTOCAST_DATASETS,./datasets}/lattice_boltzmann"
batch_size: 16
n_steps_input: 1
n_steps_output: 4
stride: 1
verbose: false
use_normalization: false
normalization_stats:
  # TODO
  stats:
    mean:
      velocity_x: 0.0
      velocity_y: 0.0
      rho: 0.0
      vorticity: 0.0
    std:
      velocity_x: 1.0
      velocity_y: 1.0
      rho: 1.0
      vorticity: 1.0
    mean_delta:
      velocity_x: 0.0
      velocity_y: 0.0
      rho: 0.0
      vorticity: 0.0
    std_delta:
      velocity_x: 1.0
      velocity_y: 1.0
      rho: 1.0
      vorticity: 1.0
  core_field_names: ["velocity_x", "velocity_y", "rho", "vorticity"]
  constant_field_names: []
num_workers: 0
