# Evaluation configuration for processor models

defaults:
  - default

# Processor models can use additional metrics
metrics:
  - mse
  - mae
  - nmse
  - nmae
  - rmse
  - nrmse
  - vmse
  - vrmse
  - linf
  - psrmse
  - psrmse_low
  - psrmse_mid
  - psrmse_high
  - psrmse_tail
  - pscc
  - pscc_low
  - pscc_mid
  - pscc_high
  - pscc_tail
  - crps
  - fcrps
  - afcrps
  - energy
  - ssr
  - winkler

max_rollout_steps: 25
