_target_: autocast.decoders.dc.DCDecoder
in_channels: 4
out_channels: ${oc.select:datamodule.n_channels, null}
hid_channels: [256, 128]
hid_blocks: [3, 3]
kernel_size: 3
stride: 2
spatial: 2
pixel_shuffle: true
periodic: true
dropout: null
