_target_: autocast.decoders.dc.DCDecoder
in_channels: 8
out_channels: ${oc.select:datamodule.n_channels, null}
hid_channels: [512, 256, 128]
hid_blocks: [3, 3, 3]
kernel_size: 3
stride: 2
spatial: 2
norm: layer
pixel_shuffle: false
periodic: false
dropout: 0.05
ffn_out_scale: 1.0e-2
