# @package _global_
defaults:
  - /distributed: ddp_4gpu_slurm
  - override /datamodule: conditioned_navier_stokes
  - override /encoder@model.encoder: permute_concat
  - override /decoder@model.decoder: channels_last
  - override /processor@model.processor: vit_azula_large
  - override /optimizer: adamw_half
  - _self_

experiment_name: ablation_crps_variant_fair_conditioned_navier_stokes

datamodule:
  use_normalization: true
  batch_size: 32

float32_matmul_precision: high

logging:
  wandb:
    enabled: true

output:
  skip_test: true

optimizer:
  learning_rate: 2e-4
  warmup: 0

model:
  train_in_latent_space: false
  n_members: 8
  encoder:
    with_constants: true
  processor:
    hidden_dim: 568
    num_heads: 8
    n_layers: 12
    n_noise_channels: 1024
  loss_func:
    _target_: autocast.losses.ensemble.FairCRPSLoss
  train_metrics:
    fcrps:
      _target_: autocast.metrics.ensemble.FairCRPS
    fcrps_mae_term:
      _target_: autocast.metrics.ensemble.FairCRPSMAETerm
    fcrps_spread_term:
      _target_: autocast.metrics.ensemble.FairCRPSSpreadTerm
  val_metrics:
    fcrps:
      _target_: autocast.metrics.ensemble.FairCRPS
    fcrps_mae_term:
      _target_: autocast.metrics.ensemble.FairCRPSMAETerm
    fcrps_spread_term:
      _target_: autocast.metrics.ensemble.FairCRPSSpreadTerm
    spread:
      _target_: autocast.metrics.ensemble.EnsembleSpread
    multicoverage:
      _target_: autocast.metrics.MultiCoverage
    multiwinkler:
      _target_: autocast.metrics.ensemble.MultiWinkler
